import 'package:flutter/material.dart';
import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:pills_good_project/screen/manual_search_disease.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: Material(
          child: ManualSearchScreen(),
        ),
      ),
    );
  }
}

class ManualSearchScreen extends StatefulWidget {

  @override
  _ManualSearchScreenState createState() => _ManualSearchScreenState();


}


class _ManualSearchScreenState extends State<ManualSearchScreen> {
  final _controller = TextEditingController();
  String _result = ''; // 결과를 저장할 변수
  List<String> _resultList = [];  // 여기를 수정했습니다.
  //late String selectedValue; // 클래스 변수로 selectedValue 선언
  String? selectedPill; // late를 제거하고 nullable로 선언
  bool _isSearchPerformed=false; //검색이 수행되었는지 여부를 추적하는 변수

  @override
  void initState() {
    super.initState();
    _resultList = _result.split('\n');
  }

  void makePostRequest() async {
    var headers = {'Content-Type': 'application/json'};
    var request = http.Request('POST', Uri.parse('https://73f1-124-51-164-190.ngrok-free.app/api/v1/drug-research'));
    request.body = json.encode({
      "drugName": _controller.text
    });
    request.headers.addAll(headers);

    try {
      http.StreamedResponse response = await request.send();

      if (response.statusCode == 200) {
        String responseString = await response.stream.bytesToString();
        print('Response String: $responseString'); // 서버 응답 출력
        Map<String, dynamic> responseJson = jsonDecode(responseString);

        if (responseJson.containsKey('data')) {
          List<dynamic> data = responseJson['data'];
          setState(() {
            _isSearchPerformed=true; //검색이 수행되었다고 상태 업데이트
            _result = data.join('\n');
            _resultList = _result.split('\n'); // 여기에서 초기화
          });
        } else {
          print('The key "data" does not exist in the response'); // data 키가 없는 경우 출력
        }
      } else {
        setState(() {
          _result = 'Error: ${response.reasonPhrase}';
          _isSearchPerformed=false; //에러 발생시 검색 수행 상태를 false로 업데이트
        });
      }
    } catch (e) {
      print('Exception occured: $e'); // 예외 발생 시 출력
      setState((){
        _isSearchPerformed=false; //예외 발생 시 검색 수행 상태를 false로 업데이트
      });
    }
  }




  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Material(
      child: Column(
      children: [
        Container(
          width: 380,
          height: 825,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 380,
                top: 825,
                child: Transform(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-3.14),
                  child: Container(
                    width: 380,
                    height: 825,
                    decoration: BoxDecoration(
                      gradient: LinearGradient(
                        begin: Alignment(0.00, -1.00),
                        end: Alignment(0, 1),
                        colors: [Color(0xFFFCE3A7), Color(0xFFFFFAEE)],
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 63,
                top: 66,
                child: Text(
                  '어떤 약을 복용하실건가요?',
                  style: TextStyle(
                    color: Color(0xFF3F3F3F),
                    fontSize: 23,
                    fontFamily: 'Pretendard',
                    fontWeight: FontWeight.w600,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 64,
                top: 93,
                child: Text(
                  '필스 굿의 검색 기능을 통해 알아보실 수 있어요.',
                  style: TextStyle(
                    color: Color(0xFF3F3F3F),
                    fontSize: 13,
                    fontFamily: 'Pretendard',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 64,
                top: 678,
                child: ElevatedButton(
                  onPressed: () {
                    // 버튼 클릭 시 실행될 함수
                    Navigator.push(
                      context,
                      MaterialPageRoute(
                        builder: (context) => ManualSearchDisease(selectedPill: selectedPill ?? ''),
                      ),
                    );
                  },
                  style: ElevatedButton.styleFrom(
                    primary: Color(0xFFFF4C39), // 버튼 배경색
                    onPrimary: Color(0xFFFFFAEE), // 버튼 텍스트 색상
                    textStyle: TextStyle(
                      fontSize: 16,
                      fontFamily: 'Pretendard',
                      fontWeight: FontWeight.w600,
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(21), // 버튼 모서리 둥글기
                    ),
                    minimumSize: Size(252, 42), // 버튼 크기
                    elevation: 4, // 버튼 그림자
                  ),
                  child: Text('제출하기'),
                ),
              ),


              Positioned(
                left: 275,
                top: 162,
                child: GestureDetector(
                  onTap: () {
                    makePostRequest(); // 여기에 makePostRequest 함수 호출
                  },

                  child: Container(
                    width: 37,
                    height: 32,
                    child: Image.asset('./assets/searchButton.png',
                        fit: BoxFit.fill),
                  ),
                ),
              ),

              Positioned(
                left: 60,
                top: 200,
                child: Material(
                  color: Colors.transparent,
                  child: Container(
                    width: MediaQuery.of(context).size.width - 100,
                    height: 220,
                    child: Visibility( // Visibility 위젯을 검색 결과 목록에만 적용
                      visible: _isSearchPerformed && _resultList.isNotEmpty,
                      child: ListView.builder(
                        itemCount: _resultList.length,
                        itemBuilder: (context, index) {
                          return InkWell(
                            onTap: () {
                              setState(() {
                                selectedPill = _resultList[index];
                                _controller.clear(); // TextField의 내용을 지웁니다.
                              });
                            },
                            child: Container(
                              width: 252,
                              height: 34,
                              margin: EdgeInsets.symmetric(vertical: 4),
                              decoration: ShapeDecoration(
                                color: Colors.white,
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(21),
                                ),
                                shadows: [
                                  BoxShadow(
                                    color: Color(0x7F000000),
                                    blurRadius: 4,
                                    offset: Offset(0, 0),
                                    spreadRadius: 0,
                                  )
                                ],
                              ),
                              child: Center(
                                child:Padding(
                                  padding:EdgeInsets.all(8.0),
                                  child: Text(
                                    _resultList[index],
                                    textAlign:TextAlign.center, //텍스트 가운데 정렬
                                    style: TextStyle(
                                      color: Colors.grey[850],
                                      fontSize: 12,

                                    ),
                                  ),
                                  
                                )
                                
                              ),
                            ),
                          );
                        },
                      ),
                      replacement: SizedBox.shrink(), // 검색 결과가 없을 때는 아무것도 표시하지 않음
                    ),
                  ),
                ),
              ),


              Positioned(
                left: 67,
                top: 136,
                child: Text(
                  '제품명 ',
                  style: TextStyle(
                    color: Color(0xFF3F3F3F),
                    fontSize: 13,
                    fontFamily: 'Pretendard',
                    fontWeight: FontWeight.w600,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 57,
                top: 448,
                child: Container(
                  width: 268,
                  height: 181,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(19),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x7F000000),
                        blurRadius: 4,
                        offset: Offset(0, 0),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 82,
                top: 472,
                child: Text(
                  '나의 알약 목록',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 12,
                    fontFamily: 'Pretendard',
                    fontWeight: FontWeight.w600,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 77,
                top: 491,
                child: Container(
                  width: 79,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 3,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: Color(0xFFFF4C39),
                      ),
                    ),
                  ),
                ),
              ),

              Positioned(
                left: 63,
                top: 162,
                child: Container(
                  width: 209,
                  height: 31,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 1.30, color: Color(0xFFFF4C39)),
                      borderRadius: BorderRadius.circular(8),
                    ),
                  ),
                  child: Material(
                    color: Colors.transparent, // Material의 배경색을 투명하게 설정
                    child: TextField(
                      controller: _controller,
                      textAlign: TextAlign.center, // hintText를 가운데 정렬
                      style: TextStyle(color: Colors.black), // 사용자 입력 텍스트의 색상을 검은색으로 설정
                      decoration: InputDecoration(
                        hintText: 'Enter drug name',
                        hintStyle: TextStyle(color: Colors.grey), // hintText의 스타일을 연회색으로 설정
                        border: InputBorder.none, // TextField의 테두리를 제거하여 Container의 테두리를 사용
                        contentPadding: EdgeInsets.fromLTRB(0, 10, 0, 6), // 좌, 상, 우, 하 패딩
                      ),
                    ),
                  ),
                ),
              ),


              /*
              Positioned(
                left: 100,
                top: 531,
                child: Container(
                  width: 180,
                  height: 100,
                child: Text(
                  selectedPill ?? ' ',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 13,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              ),*/

              //알약 이름 뜨는 곳
              Positioned(
              left:77,
              top:498,

              child: selectedPill != null ? Container(
                width: 219,
                height: 28,
                child: Stack(
                  children: [
                    Positioned(
                      left: 0,
                      top: 0,
                      child: Container(
                        width: 219,
                        height: 28,
                        decoration: ShapeDecoration(
                          color: Color(0xFFFFFCFC),
                          shape: RoundedRectangleBorder(
                            side: BorderSide(width: 1, color: Color(0xFFA0A0A0)),
                            borderRadius: BorderRadius.circular(10),
                          ),
                        ),
                      ),
                    ),
                    Positioned(
                      left: 19,
                      top: 4,
                      child: Container(
                        width: 175,
                        height: 20,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 0,
                              child: Container(
                                width: 156,
                                height: 20,
                                decoration: BoxDecoration(color: Color(0xFFFFFFFF)),
                              ),
                            ),
                            Positioned(
                              left: 5,
                              top: 3,
                              child: SizedBox(
                                width: 170,
                                height: 14,
                                child: Text(selectedPill ?? ' ',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 12,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                    height: 0,
                                  ),
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                    Positioned(
                      left: 191,
                      top: 4,
                      child: Container(
                        width: 18,
                        height: 20,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 0,
                              child: Container(
                                width: 18,
                                height: 20,
                                decoration: ShapeDecoration(
                                  color: Color(0xB5A3A3A3),
                                  shape: OvalBorder(),
                                ),
                              ),
                            ),
                            Positioned(
                              left: 5,
                              top: 3,
                              child: Text(
                                'x',
                                textAlign: TextAlign.center,
                                style: TextStyle(
                                  color: Colors.white,
                                  fontSize: 10,
                                  fontFamily: 'Inter',
                                  fontWeight: FontWeight.w400,
                                  height: 0,
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                  ],
                ),
              ) : SizedBox.shrink(),

              ),
            ],
          ),
        ),
      ],
      ),
    ),
    );
  }
}


/*
import 'package:flutter/material.dart';
import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:pills_good_project/screen/manual_search_disease.dart';

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: Text('수동 검색')),
        body: Material(
          child: ManualSearchScreen(),
        ),
      ),
    );
  }
}

class ManualSearchScreen extends StatefulWidget {

  @override
  _ManualSearchScreenState createState() => _ManualSearchScreenState();
}



class _ManualSearchScreenState extends State<ManualSearchScreen> {
  final _controller = TextEditingController();
  String _result = ''; // 결과를 저장할 변수
  List<String> _resultList = [];  // 여기를 수정했습니다.
  //late String selectedValue; // 클래스 변수로 selectedValue 선언
  String? selectedPill; // late를 제거하고 nullable로 선언


  //List<String> _resultList;

  @override
  void initState() {
    super.initState();
    _resultList = _result.split('\n');
  }

  void makePostRequest() async {
    var headers = {'Content-Type': 'application/json'};
    var request = http.Request('POST', Uri.parse('https://ab94-124-51-164-190.ngrok-free.app/api/v1/drug-research'));
    request.body = json.encode({
      "drugName": _controller.text
    });
    request.headers.addAll(headers);

    try {
      http.StreamedResponse response = await request.send();

      if (response.statusCode == 200) {
        String responseString = await response.stream.bytesToString();
        print('Response String: $responseString'); // 서버 응답 출력
        Map<String, dynamic> responseJson = jsonDecode(responseString);

        if (responseJson.containsKey('data')) {
          List<dynamic> data = responseJson['data'];
          setState(() {
            _result = data.join('\n');
            _resultList = _result.split('\n'); // 여기에서 초기화
          });
        } else {
          print('The key "data" does not exist in the response'); // data 키가 없는 경우 출력
        }
      } else {
        setState(() {
          _result = 'Error: ${response.reasonPhrase}';
        });
      }
    } catch (e) {
      print('Exception occured: $e'); // 예외 발생 시 출력
    }
  }



  void printDataValues(String jsonString) {
    Map<String, dynamic> jsonData = jsonDecode(jsonString);
    List<dynamic> dataValues = jsonData['data'];

    for (var value in dataValues) {
      print(value);
    }
  }



  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(8.0),
      child: Column(
        children: <Widget>[
          Material(
            child: TextField(
              controller: _controller,
              decoration: InputDecoration(labelText: 'Enter drug name'),
            ),
          ),
          ElevatedButton(
            child: Text('Search'),
            onPressed: makePostRequest,
          ),
          //Text(_result), // _result를 화면에 표시
          Container(
            height: 300, // 적절한 높이 값을 설정하세요.
            child: ListView.builder(
              itemCount: _resultList.length,
              itemBuilder: (context, index) {
                return TextButton(
                  child: Text(_resultList[index]),
                  onPressed: () {
                    setState(() {
                      selectedPill = _resultList[index]; // 클래스 변수 업데이트
                    });

                    // String selectedValue = _resultList[index];
                    //selectedPill = _resultList[index]; // 클래스 변수 업데이트

                    print('선택한 약: $selectedPill');
                  },
                );
              },
            ),
          ),

          Text(selectedPill ?? ' '),
          //Text(selectedValue),
          //Text(selectedValue ?? '기본값'),



          ElevatedButton(
              child: Text('submit'),
              onPressed: ()  {
                Navigator.push(
                  context,
                  MaterialPageRoute(
                    builder: (context) => ManualSearchDisease(selectedPill: selectedPill ?? ''),
                    //builder: (context) => ResultPage(selectedValue: selectedValue, di_edi_code: 642100410),
                  ),
                );


              }),

        ],
      ),
    );
  }
}


*/

//////////////////////////////////////////////////////////////////

/*
import 'package:flutter/material.dart';
import 'dart:convert';
import 'package:http/http.dart' as http;

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: Text('Drug Research App')),
        body: Material(
          child: ManualSearchScreen(),
        ),
      ),
    );
  }
}

class ManualSearchScreen extends StatefulWidget {
  @override
  _ManualSearchScreenState createState() => _ManualSearchScreenState();
}

class _ManualSearchScreenState extends State<ManualSearchScreen> {
  final _controller = TextEditingController();
  String _result = ''; // 결과를 저장할 변수
  //String _result = ''; // 결과를 저장할 변수


  void makePostRequest() async {
    var headers = {'Content-Type': 'application/json'};
    var request = http.Request('POST', Uri.parse('https://ab94-124-51-164-190.ngrok-free.app/api/v1/drug-research'));
    request.body = json.encode({
      "drugName": _controller.text
    });
    request.headers.addAll(headers);

    try {
      http.StreamedResponse response = await request.send();

      if (response.statusCode == 200) {
        String responseString = await response.stream.bytesToString();
        print('Response String: $responseString'); // 서버 응답 출력
        Map<String, dynamic> responseJson = jsonDecode(responseString);

        if (responseJson.containsKey('data')) {
          List<dynamic> data = responseJson['data'];
          setState(() {
            _result = data.join('\n');
          });
        } else {
          print('The key "data" does not exist in the response'); // data 키가 없는 경우 출력
        }
      } else {
        setState(() {
          _result = 'Error: ${response.reasonPhrase}';
        });
      }
    } catch (e) {
      print('Exception occured: $e'); // 예외 발생 시 출력
    }
  }



  void printDataValues(String jsonString) {
    Map<String, dynamic> jsonData = jsonDecode(jsonString);
    List<dynamic> dataValues = jsonData['data'];

    for (var value in dataValues) {
      print(value);
    }
  }



  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(8.0),
      child: Column(
        children: <Widget>[
      Material(
        child: TextField(
          controller: _controller,
          decoration: InputDecoration(labelText: 'Enter drug name'),
        ),
      ),
      ElevatedButton(
        child: Text('Search'),
        onPressed: makePostRequest,
      ),

          Text(_result), // _result를 화면에 표시
        ],
      ),
    );
  }
}

*/

/*
class ManualSearchScreen extends StatefulWidget {
  @override

  _ManualSearchScreenState createState() => _ManualSearchScreenState();
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          ManualSearchScreen(),
        ]),
      ),
    );
  }
}

class _ManualSearchScreenState extends State<ManualSearchScreen> {
  final TextEditingController _controller = TextEditingController();
  String _displayText = '';  // 새로운 상태 변수


  /*void makePostRequest(String drugName) async {
    var headers = {'Content-Type': 'application/json'};
    var request = http.Request('POST', Uri.parse('https://ab94-124-51-164-190.ngrok-free.app/api/v1/drug-research'));
    request.body = json.encode({"drugName": drugName});
    request.headers.addAll(headers);

    http.StreamedResponse response = await request.send();

    if (response.statusCode == 200) {
      print(await response.stream.bytesToString());
    } else {
      print(response.reasonPhrase);
    }
  }
*/






  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 380,
          height: 825,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 380,
                top: 825,
                child: Transform(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-3.14),
                  child: Container(
                    width: 380,
                    height: 825,
                    decoration: BoxDecoration(
                      gradient: LinearGradient(
                        begin: Alignment(0.00, -1.00),
                        end: Alignment(0, 1),
                        //colors: [Color(0xFFFFFF), Color(0xFFFFFF)],
                        colors: [Color(0xFFFCE3A7), Color(0xFFFFFAEE)],
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 63,
                top: 66,
                child: Text(
                  '어떤 약을 복용하실건가요?',
                  style: TextStyle(
                    color: Color(0xFF3F3F3F),
                    fontSize: 23,
                    fontFamily: 'Pretendard',
                    fontWeight: FontWeight.w600,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 64,
                top: 93,
                child: Text(
                  '필스 굿의 검색 기능을 통해 알아보실 수 있어요.',
                  style: TextStyle(
                    color: Color(0xFF3F3F3F),
                    fontSize: 13,
                    fontFamily: 'Pretendard',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 64,
                top: 678,
                child: Container(
                  width: 252,
                  height: 42,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 252,
                          height: 42,
                          decoration: ShapeDecoration(
                            color: Color(0xFFFF4C39),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(21),
                            ),
                            shadows: [
                              BoxShadow(
                                color: Color(0x3F000000),
                                blurRadius: 4,
                                offset: Offset(0, 0),
                                spreadRadius: 0,
                              )
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 98,
                        top: 11,
                        child: Text(
                          '제출하기',
                          style: TextStyle(
                            color: Color(0xFFFFFAEE),
                            fontSize: 16,
                            fontFamily: 'Pretendard',
                            fontWeight: FontWeight.w600,
                            height: 0,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),

              Positioned(
                left: 67,
                top: 136,
                child: Text(
                  '제품명 ',
                  style: TextStyle(
                    color: Color(0xFF3F3F3F),
                    fontSize: 13,
                    fontFamily: 'Pretendard',
                    fontWeight: FontWeight.w600,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 57,
                top: 448,
                child: Container(
                  width: 268,
                  height: 181,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(19),
                    ),

                    shadows: [
                      BoxShadow(
                        color: Color(0x7F000000),
                        blurRadius: 4,
                        offset: Offset(0, 0),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                  child: Center(  // Center 위젯 추가
                    child: Text(_displayText),  // 화면에 상태 출력
                  ),
                ),

              ),

              Positioned(
                left: 82,
                top: 472,
                child: Text(
                  '나의 알약 목록',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 12,
                    fontFamily: 'Pretendard',
                    fontWeight: FontWeight.w600,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 77,
                top: 491,
                child: Container(
                  width: 79,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 3,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: Color(0xFFFF4C39),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 63,
                top: 162,
                child: Container(
                  width: 209,
                  height: 31,
                  child: Material(  // Material 위젯 추가
                    child: TextField(
                      controller: _controller,// TextField 위젯 추가
                      decoration: InputDecoration(
                        border: InputBorder.none,
                        contentPadding: EdgeInsets.all(15.0),
                        labelText: '제품명을 입력해주세요',
                      ),
                    ),
                  ),
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 1.30, color: Color(0xFFFF4C39)),
                      borderRadius: BorderRadius.circular(8),
                    ),
                  ),
                ),
              ),

              Positioned(
                left: 275,
                top: 162,
                child: Container(
                  width: 37,
                  height: 32,
                  child: ElevatedButton(
                    onPressed: () {
                      makePostRequest(_controller.text); // drugName 인자 전달
                      //makePostRequest(_controller.text);
                      setState(() {  // 상태 업데이트
                        _displayText = '${_controller.text}';
                      });
                      print('Search button is pressed');
                      print(_displayText);
                    },
                    child: Icon(Icons.search, color: Colors.white, size: 20.0),
                ),
              ),
              ),

              /*ElevatedButton(
                onPressed: makePostRequest, // 버튼이 클릭되면 makePostRequest 함수가 실행됩니다.
                child: Text('Send Request'),
              ),*/
            ],
          ),
        ),
      ],
    );
  }
}

*/


/*
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:pills_good_project/storage_service.dart';
import 'package:pills_good_project/screen/add_item.dart';
//import 'package:flutter/storage_service.dart';
import 'cloud_storage_demo.dart'; // CloudStorageDemo 페이지를 import 합니다.

class ManualSearchScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final Storage storage=Storage();
    return Scaffold(
      appBar: AppBar(
        title: Text('수동검색2'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text('수동검색 화면입니다'),
            ElevatedButton(
                child: Text('firebase'),
                onPressed: () {
                  Navigator.push(
                    context,
                    MaterialPageRoute(
                      builder: (context) => AddItem(),
                    ),
                  );


                  /*Navigator.push(
                    context,
                    MaterialPageRoute(builder: (context) => CloudStorageDemo()),*/
                  /* );*/
                }),
            ElevatedButton(
                child: Text('upload File'),
                onPressed: () async {
                  final results=await FilePicker.platform.pickFiles(
                  allowMultiple:false,
                  type:FileType.custom,
                  allowedExtensions:['png','jpg'],
                  );

                  if(results==null){
                    ScaffoldMessenger.of(context).showSnackBar(
                      const SnackBar(
                        content:Text('No file selected'),
                      ),
                    );
                    return null;
                  }

                  final path=results.files.single.path!;
                  final fileName=results.files.single.name;

                  try {
                    await storage.uploadFile(path, fileName);
                    print('Upload complete');
                    print('File path: $path');
                    print('File name: $fileName');
                  } catch (e) {
                    print('Failed to upload file: $e');
                  }

                  storage
                      .uploadFile(path, fileName)
                      .then((value)=>print('Done'));

                  print(path);
                  print(fileName);


                  /*Navigator.push(
                    context,
                    MaterialPageRoute(builder: (context) => CloudStorageDemo()),*/
                 /* );*/
                }),
          ],
        ),
      ),
    );
  }
}
*/

///////////////////////////////////////////////////////
////////////////////////////////////////////////////////
/*
import 'package:flutter/material.dart';

class ManualSearchScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('수동검색'),
      ),
      body: Center(
        child: Text('수동검색 화면입니다'),
      ),
    );
  }
}
*/

