// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgbD2ZsyGlhhzwiB37gBJWfVc4o00uwEc',
    appId: '1:732885620876:web:8232c29c4ce5ede86a43a9',
    messagingSenderId: '732885620876',
    projectId: 'pills-good',
    authDomain: 'pills-good.firebaseapp.com',
    storageBucket: 'pills-good.appspot.com',
    measurementId: 'G-GR39VKM7DC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbJaJEBdFQ5cV7MxD0IxgW-dCZvITkQYI',
    appId: '1:732885620876:android:6cb51095ce96237a6a43a9',
    messagingSenderId: '732885620876',
    projectId: 'pills-good',
    storageBucket: 'pills-good.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA82m9pNC8rqcJKzRE3-VZj66epu9ZJKaM',
    appId: '1:732885620876:ios:5493d55831bb3ef26a43a9',
    messagingSenderId: '732885620876',
    projectId: 'pills-good',
    storageBucket: 'pills-good.appspot.com',
    iosBundleId: 'com.example.pillsGoodProject',
  );
}
